### ISSUE TITLE
Inconsistent `Error: abort` on clone/start

### ISSUE THREAD

**Issue by andymikulski** [as2d/as2d-example#6]
I've found after cloning and starting this repo, the web page seems to error out occasionally. Sometimes the page loads fine, other times it throws `Error: abort:  at assembly/index.ts:29:2` in the console.

I've attached a gif here which demonstrates the page refreshing and occasionally working/not working:

![as2d-broken](https://user-images.githubusercontent.com/2767162/73185316-d7309900-40eb-11ea-9f29-874d29752878.gif)

**Comment by jtenner** [comment]
Hey! Thanks for your interest in this project. Can you try upgrading to assemblyscript version `0.9.0`?

**Comment by andymikulski** [comment]
Thanks for the quick response! After updating to `0.9.0`, the error still comes up, but it _seems_ like it is working with fewer refreshes. Perhaps this is an AS issue, then?

**Comment by jtenner** [comment]
```
wasm-520f769e:36 Uncaught (in promise) RuntimeError: float unrepresentable in integer range
    at wasm-function[35]:0x1802
    at Object.wrap [as init] (http://localhost:1234/src.e31bb0bc.js:2437:12)
    at postInstantiate (http://localhost:1234/src.e31bb0bc.js:3685:8)
```

Well this looks fun :)

```ts
  let seed = JSMath.random() * <f64>u64.MAX_VALUE
  NativeMath.seedRandom(<i64>seed);
```

We don't really need anything special for random number generation here, so it's entirely possible to use `reinterpret<i64>(JSMath.random())` as the seed value.  You can change the beginning of the init script to look like this:

```ts
NativeMath.seedRandom(reinterpret<i64>(JSMath.random()));
```

I will fix this issue very soon in a pull request, but you should try it out for yourself.

**Comment by MaxGraey** [comment]
> Uncaught (in promise) RuntimeError: float unrepresentable in integer range

That's limitation of WebAssembly. if float to int not fit into MAX_INT engine will throw exception like that.

To avoid this in current situation you cout slightly modify your code:
```ts
 let seed = JSMath.random() * f64.MAX_SAFE_INTEGER;
 NativeMath.seedRandom(<i64>seed);
```
